version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.1
    container_name: zookeeper
    # networks:
    #   - batch_network    
    ports:
      - 2181:2181      
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.0.1
    hostname: 13.124.251.248
    container_name: broker
    # networks:
    #   - batch_network    
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://13.124.251.248:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100
      KAFKA_MESSAGE_MAX_BYTES: 3072000
    volumes:
      - ./data/kafka-data:/var/lib/kafka/data

  kafka-ui:
     image: provectuslabs/kafka-ui
     container_name: kafka-ui
     ports:
       - 8000:8080
     restart: always
     environment:
       - KAFKA_CLUSTERS_0_NAME=aws
       - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:9092
       - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181